# Generated by Django 2.2.5 on 2020-03-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image_url_https', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('screen_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('friends_count', models.IntegerField(default=0)),
                ('followers_count', models.IntegerField(default=0)),
                ('ratio', models.FloatField()),
                ('statuses_count', models.IntegerField(default=0)),
                ('created_at', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('favourites_count', models.IntegerField(default=0)),
            ],
        ),
    ]
