# Generated by Django 2.2.5 on 2020-03-09 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relation_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.CharField(max_length=100)),
                ('followed', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image_url_https', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('friends_count', models.IntegerField(default=0)),
                ('followers_count', models.IntegerField(default=0)),
                ('ratio', models.FloatField(default=0)),
                ('screen_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Relation_Info')),
            ],
        ),
    ]
