# Generated by Django 2.2.5 on 2020-03-09 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='screen_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Relation_Info'),
        ),
    ]
