# Generated by Django 2.2.5 on 2020-03-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='ratio',
            field=models.FloatField(default=0),
        ),
    ]
