# Generated by Django 2.2.5 on 2020-03-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200302_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image_url_https', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('screen_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('friends_count', models.IntegerField(default=0)),
                ('followers_count', models.IntegerField(default=0)),
                ('ratio', models.FloatField(default=0)),
                ('statuses_count', models.IntegerField(default=0)),
                ('created_at', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('favourites_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='User_Info',
            new_name='Friend_Info',
        ),
    ]
