# Generated by Django 2.2.5 on 2020-03-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200303_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower_info',
            name='my_screen_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='friend_info',
            name='my_screen_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
