# Generated by Django 2.2.5 on 2020-03-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200306_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower_info',
            name='created_at',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='friend_info',
            name='created_at',
            field=models.DateField(default=0),
        ),
    ]
