# Generated by Django 2.2.5 on 2020-03-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200306_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.CharField(max_length=100)),
                ('followed', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image_url_https', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('screen_name', models.CharField(max_length=100)),
                ('friends_count', models.IntegerField(default=0)),
                ('followers_count', models.IntegerField(default=0)),
                ('ratio', models.FloatField(default=0)),
            ],
        ),
    ]
